language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"
  - DJANGO="Django<1.11"

install:
  - pip install $DJANGO

script:
  - python runtests.py
